from __future__ import annotations
import json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data';REPORTS=ROOT/'reports'
SCHEMA={'version':'1.0','principle':'Sell intelligence, not identities.','entities':{'market':{'fields':['market_id','country','region','source_count']},'sector':{'fields':['sector_id','name']},'problem':{'fields':['problem_id','market_id','sector_id','mechanism_id','title','evidence_score','recurrence_score','confidence','observation_count']},'mechanism':{'fields':['mechanism_id','name','cross_market_count','cross_sector_count']},'evidence':{'fields':['evidence_id','problem_id','source_type','source_domain','observed_at','quality','independent','public_or_permitted']},'trend':{'fields':['trend_id','problem_id','period','direction','magnitude','confidence']},'intelligence_product':{'fields':['product_id','audience','scope','delivery','aggregation_level']},'privacy':{'fields':['identity_collection_allowed','raw_identity_sale_allowed','raw_private_content_sale_allowed','aggregation_required','retention_policy']}}}
def main():
 DATA.mkdir(exist_ok=True);REPORTS.mkdir(exist_ok=True);now=datetime.now(timezone.utc).isoformat(); obj={'generated_at':now,**SCHEMA,'privacy':{'identity_collection_allowed':'only where lawfully necessary for a defined purpose','raw_identity_sale_allowed':False,'raw_private_content_sale_allowed':False,'aggregation_required':True,'retention_policy':'minimise and delete when no longer necessary; customer-specific retention must be documented'}};(DATA/'intelligence_schema.json').write_text(json.dumps(obj,indent=2),encoding='utf-8');(REPORTS/'intelligence-schema.md').write_text('# Problem Radar — Intelligence Data Model\n\nThe platform is modelled around markets, sectors, problems, mechanisms, evidence and trends. Personal identities are not a commercial entity in the model.\n\n## Core query\n\n`market → sector → problem → mechanism → evidence → trend → action`\n\n## Privacy boundary\n\nRaw identities and private content are excluded from commercial outputs. Evidence provenance should be retained only to the extent necessary to support confidence, auditing and lawful use.\n\n## Product principle\n\n**Sell intelligence, not identities.**\n',encoding='utf-8');print('[radar] intelligence schema generated')
if __name__=='__main__':main()
