from __future__ import annotations
import json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data';REPORTS=ROOT/'reports'
def load(n,d=None):
 try:return json.loads((DATA/n).read_text(encoding='utf-8'))
 except Exception:return d if d is not None else {}
def main():
 q=load('evidence_resolution_queue.json',{}); dossiers=(REPORTS/'evidence-dossiers.md').read_text(encoding='utf-8') if (REPORTS/'evidence-dossiers.md').exists() else ''; now=datetime.now(timezone.utc).isoformat(); cands=q.get('candidates',[])
 lines=["# Problem Radar — Global Intelligence Report","",f"Generated: {now}","","## Executive summary","","Problem Radar is designed as a global problem-intelligence system. Nigeria is the initial market, but the underlying model compares recurring problems, mechanisms and evidence across markets.","","The current research indicates recurring signals around trust/verification, service reliability, price/access and workflow/information friction. These are research themes, not automatically validated businesses.","","## Evidence standard","","A recurring observation is not treated as independent confirmation. Commercial conclusions require source diversity, provenance, current external corroboration and a clearly defined buyer problem.","","## Current resolution themes",""]
 for x in cands[:10]: lines += [f"### {x['id']} — {x['mechanism'].replace('_',' ').title()}",f"- Cluster count: {x['cluster_count']}",f"- Observations represented: {x['observation_count']}",f"- Independent source domains currently represented: {x['source_domain_count']}",f"- Categories: {', '.join(x['categories'])}",f"- Average evidence score: {x['average_evidence_score']}",f"- Average recurrence score: {x['average_recurrence_score']}","- Status: requires external resolution",""]
 lines += ["## Intelligence products to test","","1. **Problem Trend Briefs** — recurring problems by country/sector/time period.","2. **Service Friction Intelligence** — aggregated reliability and complaint patterns.","3. **Verification Intelligence** — emerging false-claim, impersonation and authenticity patterns.","4. **Sector Intelligence API** — machine-readable aggregated signals with provenance and confidence.","5. **Opportunity Intelligence** — validated unmet needs for innovation teams and founders.","","## Privacy boundary","","Problem Radar sells aggregated intelligence, provenance, confidence and trends. Names, contact lists, identifiable complaints and private messages are not commercial outputs.","","## Buyer-validation questions","","- Which decisions would this intelligence change?","- What data do existing internal/regulatory systems fail to capture?","- How frequently does the buyer need the signal?","- What is the measurable cost of missing it?","- What evidence threshold is acceptable for operational action?","- Would the buyer pay for a report, dashboard, API or alert?","","## Next research step","","Resolve the highest-value themes against independent primary/official sources, quantify affected populations where possible, and interview prospective buyers before building a full commercial dashboard."]
 (REPORTS/'global-intelligence-report.md').write_text('\n'.join(lines)+'\n\n## Evidence dossiers\n\n'+dossiers,encoding='utf-8');print(f'[radar] generated report with {min(10,len(cands))} resolution themes')
if __name__=='__main__':main()
